name: "Validation"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('requirements.txt') }}
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 taskkit tests
    - name: Lint with mypy
      run: |
        mypy taskkit tests
    - name: Lint with pyright
      run: |
        pyright taskkit tests

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    services:
      redis:
        image: redis:6.0
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('requirements.txt') }}
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Test with unittest
      run: |
        python -m unittest
